version: '3'
services:
  devenv:
    build:
      context: .
    image: devenv
    container_name: devenv
    volumes:
      - ./project:/root/project
      - ./nvim:/root/.config/nvim
    tty: true
