services:
  devenv:
    build:
      context: .
      dockerfile: Dockerfile.devenv
    image: devenv
    container_name: devenv
    volumes:
      - ./project:/root/project
      - ./nvim:/root/.config/nvim
    tty: true

  devweb:
    build:
      context: .
      dockerfile: Dockerfile.devweb
    image: devweb
    container_name: devweb
    volumes:
      - ./project:/root/project
      - ./nvim:/root/.config/nvim
      - ./project-outsourcing:/root/outsourcing
    ports:
      - "80:80"
      - "443:443"
    tty: true